param([string]$ExePath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts\release\小狗效率屋-v1.0.0-x64\portable\HMinus.DesktopSpike.exe'))
$ErrorActionPreference='Stop'
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
function Wait-Window([int]$ProcessId,[int]$Seconds=15){$c=New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ProcessIdProperty,$ProcessId);for($i=0;$i-lt $Seconds*5;$i++){$w=[System.Windows.Automation.AutomationElement]::RootElement.FindFirst([System.Windows.Automation.TreeScope]::Children,$c);if($w){return $w};Start-Sleep -Milliseconds 200};throw '找不到窗口'}
function Find-One($Root,[string]$Name,$Type=$null){$cs=New-Object System.Collections.Generic.List[System.Windows.Automation.Condition];if($Name-ne''){$cs.Add((New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::NameProperty,$Name)))};if($Type){$cs.Add((New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ControlTypeProperty,$Type)))};$c=if($cs.Count-eq 1){$cs[0]}else{New-Object System.Windows.Automation.AndCondition($cs.ToArray())};$Root.FindFirst([System.Windows.Automation.TreeScope]::Descendants,$c)}
function Wait-One($Root,[string]$Name,$Type=$null,[int]$Seconds=12){for($i=0;$i-lt $Seconds*5;$i++){$e=Find-One $Root $Name $Type;if($e-and !$e.Current.IsOffscreen){return $e};Start-Sleep -Milliseconds 200};throw "未找到控件：$Name"}
function Invoke-One($Element){$Element.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();Start-Sleep -Milliseconds 500}
function Select-One($Element){$Element.GetCurrentPattern([System.Windows.Automation.SelectionItemPattern]::Pattern).Select();Start-Sleep -Milliseconds 400}
function Find-CardButton($TextElement,[string]$ButtonName){$walker=[System.Windows.Automation.TreeWalker]::ControlViewWalker;$node=$TextElement;for($i=0;$i-lt 8;$i++){$node=$walker.GetParent($node);if(!$node){break};$button=Find-One $node $ButtonName ([System.Windows.Automation.ControlType]::Button);if($button-and!$button.Current.IsOffscreen){return $button}};throw "未找到卡片按钮：$ButtonName"}
function Stop-App($Process){if($Process-and!$Process.HasExited){$Process.Kill();$Process.WaitForExit()}}
$real=Join-Path $env:LOCALAPPDATA 'HMinus\DesktopSpike';$backup="$real.codex-phase5b-$(Get-Date -Format yyyyMMddHHmmssfff)";$had=Test-Path -LiteralPath $real;$app=$null;$clip=[System.Windows.Forms.Clipboard]::GetDataObject();$bitmap=$null
Get-Process HMinus.DesktopSpike -ErrorAction SilentlyContinue|Stop-Process -Force;if($had){Move-Item -LiteralPath $real -Destination $backup};New-Item -ItemType Directory -Path $real -Force|Out-Null;'{"Left":1180,"Top":420,"Width":330,"Height":520,"MonitorDeviceName":null}'|Set-Content (Join-Path $real 'window-settings.json') -Encoding utf8
try{
 Write-Host 'STEP 1 启动并确认隐私';$app=Start-Process $ExePath -PassThru;$root=Wait-Window $app.Id;if($root.Current.Name-ne'小狗效率屋'){throw "正式版窗口标题不正确：$($root.Current.Name)"};Invoke-One (Wait-One $root '我已了解并启用' ([System.Windows.Automation.ControlType]::Button));Select-One (Wait-One $root '剪贴板' ([System.Windows.Automation.ControlType]::TabItem))
 Write-Host 'STEP 2 捕获图片并置顶';$bitmap=New-Object System.Drawing.Bitmap 84,62;$graphics=[System.Drawing.Graphics]::FromImage($bitmap);$graphics.Clear([System.Drawing.Color]::FromArgb(255,174,204,180));$graphics.FillEllipse([System.Drawing.Brushes]::White,20,10,42,42);$graphics.Dispose();[System.Windows.Forms.Clipboard]::SetImage($bitmap);$summary=Wait-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text) 15
 $imageDir=Join-Path $real 'data\clipboard-images';for($i=0;$i-lt 30-and (!(Test-Path $imageDir)-or (Get-ChildItem $imageDir -Filter '*.png' -ErrorAction SilentlyContinue).Count-lt 2);$i++){Start-Sleep -Milliseconds 200};if((Get-ChildItem $imageDir -Filter '*.png').Count-lt 2){throw '未生成原图和缩略图文件'};Invoke-One (Find-CardButton $summary '置顶');$summary=Wait-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text);$null=Find-CardButton $summary '取消置顶'
 Write-Host 'STEP 3 重启后保留置顶并可取消';Stop-App $app;$app=Start-Process $ExePath -PassThru;$root=Wait-Window $app.Id;Select-One (Wait-One $root '剪贴板' ([System.Windows.Automation.ControlType]::TabItem));$summary=Wait-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text) 12;Invoke-One (Find-CardButton $summary '取消置顶');$summary=Wait-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text);$null=Find-CardButton $summary '置顶'
 Write-Host 'STEP 4 删除图片记录、原图和缩略图';Invoke-One (Find-CardButton $summary '删除');for($i=0;$i-lt 30-and (Get-ChildItem $imageDir -File -ErrorAction SilentlyContinue).Count-gt0;$i++){Start-Sleep -Milliseconds 200};if((Get-ChildItem $imageDir -File -ErrorAction SilentlyContinue).Count-gt0){throw '删除后图片目录仍有文件'};if(Find-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text)){throw '删除后图片卡片仍存在'}
 Write-Host 'STEP 5 重启后图片不恢复';Stop-App $app;$app=Start-Process $ExePath -PassThru;$root=Wait-Window $app.Id;Select-One (Wait-One $root '剪贴板' ([System.Windows.Automation.ControlType]::TabItem));Start-Sleep -Milliseconds 800;if(Find-One $root '图片 84 × 62' ([System.Windows.Automation.ControlType]::Text)){throw '已删除图片在重启后恢复'};Write-Host 'PASS v1.0.0正式版UI烟雾测试通过'}finally{if($bitmap){$bitmap.Dispose()};Stop-App $app;if($clip){[System.Windows.Forms.Clipboard]::SetDataObject($clip,$true)};if(Test-Path -LiteralPath $real){Remove-Item -LiteralPath $real -Recurse -Force};if($had-and(Test-Path -LiteralPath $backup)){Move-Item -LiteralPath $backup -Destination $real};Write-Host 'CLEANUP 已恢复用户原有数据与剪贴板'}

